---
# tasks file for nginx-install
 - name: Install nginx in RHEL/CentOS
   yum:
    name: nginx
    state: latest
   when: ansible_os_family=="RedHat"
 
 - name: Install nginx in Ubuntu
   yum:
    name: nginx
    state: latest
   when: ansible_os_family=="Debian"

 - name: "Install ufw package - RHEL/CENTOS"
   yum:
    name: ufw
    state: latest
   when: ansible_os_family == "RedHat"

 - name: "Install ufw package - Debian"
   apt:
    name: ufw
    state: latest
   when: ansible_os_family  == "Debian"

 - name: "Start ufw service"
   service:
    name: ufw
    state: started

 - name: "Modifiy nginx port"
   replace:
    path: /etc/nginx/nginx.conf
    regexp: '(listen\s+|listen\s+\[\:\:\]\:)\d+'
    replace: '\1 {{ nginx_custom_port | string }}'

 - name: "Allow ssh port"
   ufw:
    rule: allow
    port: "{{ nginx_custom_port | int }}"
   notify: restart nginx
